version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: pyrus_client
    image: pyrus_client
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
